### ISSUE TITLE
Add tab bar

### ISSUE THREAD

**Issue by laurrenreed** [laurrenreed/WWCodeDFW#8]
Add tab bar and 4 bar button items to match the InVision document. 
https://invis.io/SFDV9GZW9#/257460173_Jobs_Page
Font awesome is a great place to get free icons, and so is the Noun Project. Regardless of where you get the icons from, be sure to add the website for credit in the README.md

Tab bar tutorials:
https://code.tutsplus.com/tutorials/ios-from-scratch-with-swift-exploring-tab-bar-controller--cms-25470
https://www.youtube.com/watch?v=nFw1yVhG4r8
https://www.raywenderlich.com/160521/storyboards-tutorial-ios-11-part-1

Add icons tutorial: 
https://guides.codepath.com/ios/Adding-Image-Assets
https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/

Font Awesome: http://fontawesome.io
Noun Project: https://thenounproject.com

**Comment by agroGandhi** [comment]
Hi Lauren I'd like to work on this, are you able to give me permissions to view the project on InVision?

**Comment by laurrenreed** [comment]
Hey! I sent you a link to the InVision.. design is still being worked on, but feel free to grab this issue!

**Comment by agroGandhi** [comment]
Got it thanks

**Comment by agroGandhi** [comment]
Lauren can you email me the assets used in the InVision designs for consistency? Or should I just find similar style icons

**Comment by laurrenreed** [comment]
You can select icons from either open source site listed above. That design isn't finalized, so you're more than welcome to select what you think looks best!

**Comment by laurrenreed** [comment]
@agroGandhi I just invited you as a collaborator so that you can add yourself as an assignee and drag the issue into in progress on the project board!
