### ISSUE TITLE
Add right bar button Item to Nav bar 

### ISSUE THREAD

**Issue by laurrenreed** [laurrenreed/WWCodeDFW#9]
Add a right bar button item titled "Donate" to the Navigation bar. Add DonationsViewController to the button and a back button out of that view controller. 
Acceptance Criteria: As a user, when I select the "Donate" button at the top right corner of the screen I want to go to a new ViewController titled "Donate" that has a back button to return to the previous view. 
https://invis.io/SFDV9GZW9#/257460173_Jobs_Page

How to add right bar button item: 
https://stackoverflow.com/questions/5832098/how-to-add-a-right-bar-button-to-a-navigation-bar-in-iphone
https://www.andrewcbancroft.com/2016/04/14/adding-buttons-to-the-navigation-bar-with-storyboards/

**Comment by valosip** [comment]
I'll take it
